Building a logistic regression model from scratch for diabetes prediction

In [52]:
import numpy as np

In [53]:
class Logistic_Regression():
  def __init__(self,learning_rate,no_of_iterations):
    self.learning_rate=learning_rate
    self.no_of_iterations=no_of_iterations

  def fit(self,X,Y):
    self.m,self.n=X.shape
    self.w=np.zeros(self.n)
    self.b=0
    self.X=X
    self.Y=Y

    for i in range(self.no_of_iterations):
      self.update_weights()
  def update_weights(self):
    Y_hat=1/(1+np.exp(-(self.X.dot(self.w)+self.b)))

    dw=(1/self.m)*np.dot(self.X.T,(Y_hat-self.Y))
    db=(1/self.m)*np.sum(Y_hat-self.Y)

    self.w=self.w-self.learning_rate*dw
    self.b=self.b-self.learning_rate*db
  def predict(self, X):

    Y_pred=1/(1+np.exp(-(X.dot(self.w)+self.b)))
    Y_pred=np.where(Y_pred>0.5,1,0)
    return Y_pred

In [54]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [55]:
data=pd.read_csv("diabetes_training_data.csv")

In [56]:
data.head()

   pregnancies  glucose  bloodpressure  ...  DiabetesPEdigreefunction  age  outcome
0            4      125             84  ...                     0.137   29        1
1            1       63             51  ...                     0.278   28        0
2            3      130             78  ...                     0.078   21        0
3            3      115             79  ...                     0.108   48        1
4            2      105             89  ...                     0.078   64        1

[5 rows x 9 columns]

In [57]:
data.shape

(500, 9)

In [58]:
data.describe()

       pregnancies     glucose  ...         age     outcome
count   500.000000  500.000000  ...  500.000000  500.000000
mean      2.940000  120.142000  ...   33.166000    0.578000
std       1.778405   31.463721  ...   13.645763    0.494373
min       0.000000   23.000000  ...   21.000000    0.000000
25%       2.000000   99.000000  ...   21.000000    0.000000
50%       3.000000  119.500000  ...   29.000000    1.000000
75%       4.000000  141.250000  ...   41.000000    1.000000
max       9.000000  200.000000  ...   81.000000    1.000000

[8 rows x 9 columns]

In [59]:
data['outcome'].value_counts()

outcome
1    289
0    211
Name: count, dtype: int64

In [60]:
data.groupby('outcome').mean()

         pregnancies     glucose  ...  DiabetesPEdigreefunction        age
outcome                           ...
0           2.786730  106.507109  ...                  0.396924  31.407583
1           3.051903  130.096886  ...                  0.524619  34.449827

[2 rows x 8 columns]

In [61]:
features=data.drop(columns='outcome',axis=1)
target=data['outcome']

In [62]:
features

     pregnancies  glucose  bloodpressure  ...   bmi  DiabetesPEdigreefunction  age
0              4      125             84  ...  35.4                     0.137   29
1              1       63             51  ...  35.3                     0.278   28
2              3      130             78  ...  18.0                     0.078   21
3              3      115             79  ...  40.4                     0.108   48
4              2      105             89  ...  34.0                     0.078   64
..           ...      ...            ...  ...   ...                       ...  ...
495            2      126             78  ...  36.3                     0.210   23
496            6      178             77  ...  39.5                     0.546   21
497            3      160             81  ...  31.5                     0.176   46
498            4      127            108  ...  46.7                     0.078   32
499            2      104             48  ...  33.8                     0.568   43

[500 rows x 8 columns]

In [63]:
target

0      1
1      0
2      0
3      1
4      1
      ..
495    1
496    1
497    0
498    1
499    1
Name: outcome, Length: 500, dtype: int64

In [64]:
scaler=StandardScaler()

In [65]:
scaler.fit(features)

StandardScaler()

In [66]:
standardized_data=scaler.transform(features)

In [67]:
features=standardized_data

In [68]:
features

array([[ 0.59663654,  0.15455468,  0.80706978, ...,  0.45647453,
        -0.72720867, -0.30560198],
       [-1.09195744, -1.81794223, -1.00324171, ...,  0.44386335,
        -0.41996686, -0.37895819],
       [ 0.03377188,  0.31362701,  0.47792223, ..., -1.73787204,
        -0.85577084, -0.89245167],
       ...,
       [ 0.03377188,  1.26806099,  0.642496  , ..., -0.03536177,
        -0.64222689,  0.94145362],
       [ 0.59663654,  0.21818361,  2.12365995, ...,  1.88153869,
        -0.85577084, -0.08553334],
       [-0.52909278, -0.51354911, -1.16781548, ...,  0.25469554,
         0.21194891,  0.72138498]])

In [69]:
target=data['outcome']

In [70]:
X_train,X_test,Y_train,Y_test=train_test_split(features,target,test_size=0.2,random_state=2)

In [71]:
print(features.shape,X_train.shape,X_test.shape)

(500, 8) (400, 8) (100, 8)

In [72]:
model=Logistic_Regression(learning_rate=0.01,no_of_iterations=1000)

In [73]:
model.fit(X_train,Y_train)

In [74]:
X_train_prediction=model.predict(X_train)
training_data_accuracy=accuracy_score(Y_train,X_train_prediction)

In [75]:
training_data_accuracy

0.7475