Email Spam Detection using Logistic Regression

First let's load the csv file and visualise our dataset

In [3]:
import pandas as pd
df = pd.read_csv('email_spam_dataset_250.csv')
df.head()

                                                text label
0  Please find the attached report for this week'...   ham
1  Hi, just checking if we are still meeting tomo...   ham
2  Your order has been shipped and will arrive soon.   ham
3  Lunch at Hawaii today? Let me know if you're f...   ham
4  Exclusive deal just for you: Buy 1 get 1 free ...  spam

In [4]:
df.shape #-> (rows,columns)

(250, 2)

In [5]:
df.columns

Index(['text', 'label'], dtype='object')

In [6]:
df['label'].value_counts()

label
ham     125
spam    125
Name: count, dtype: int64

converting the spam:1 and ham:0

In [7]:
df['label'] = df['label'].map({'ham':0,'spam':1})

In [8]:
df.head()

                                                text  label
0  Please find the attached report for this week'...      0
1  Hi, just checking if we are still meeting tomo...      0
2  Your order has been shipped and will arrive soon.      0
3  Lunch at Hawaii today? Let me know if you're f...      0
4  Exclusive deal just for you: Buy 1 get 1 free ...      1

Let's vectorize the text to be a proper input

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(stop_words='english',max_features=500)
X=tfidf.fit_transform(df['text'])
Y=df['label']
print(X.shape)
print(Y.shape)

(250, 110)
(250,)

In [10]:
feature_names=tfidf.get_feature_names_out()
print(feature_names)

['10' '100' '1000' '12' '200' '2000' '24' '30' '40' '50' '500' '60' '70'
 'access' 'account' 'act' 'apply' 'approved' 'arrive' 'attached' 'bali'
 'brand' 'buy' 'card' 'cheap' 'checking' 'claim' 'click' 'confirm'
 'congratulations' 'contest' 'deal' 'discuss' 'document' 'dubai' 'earlier'
 'earn' 'easily' 'email' 'enter' 'exclusive' 'expires' 'file' 'final'
 'free' 'gift' 'hawaii' 'headphones' 'help' 'hi' 'home' 'hours'
 'immediately' 'instantly' 'iphone' 'just' 'know' 'laptop' 'let' 'limited'
 'll' 'loan' 'lunch' 'make' 'maldives' 'meeting' 'money' 'new' 'offer'
 'order' 'paris' 'plan' 'pm' 'prescription' 'previous' 'prize' 'products'
 'project' 'received' 'reminder' 'report' 'restore' 'review' 'scheduled'
 'selected' 'send' 'sent' 'shipped' 'shop' 'smartwatch' 'soon' 'suspended'
 'tablet' 'task' 'team' 'thanks' 'time' 'today' 'tomorrow' 'tonight'
 'update' 'urgent' 'vacation' 've' 'verify' 'version' 'week' 'win' 'won'
 'yesterday']

In [11]:
test=X.toarray()
for i in range(len(test[0])):
  print(feature_names[i],test[0][i])

10 0.0
100 0.0
1000 0.0
12 0.0
200 0.0
2000 0.0
24 0.0
30 0.0
40 0.0
50 0.0
500 0.0
60 0.0
70 0.0
access 0.0
account 0.0
act 0.0
apply 0.0
approved 0.0
arrive 0.0
attached 0.4640170318335872
bali 0.0
brand 0.0
buy 0.0
card 0.0
cheap 0.0
checking 0.0
claim 0.0
click 0.0
confirm 0.0
congratulations 0.0
contest 0.0
deal 0.0
discuss 0.0
document 0.0
dubai 0.0
earlier 0.0
earn 0.0
easily 0.0
email 0.0
enter 0.0
exclusive 0.0
expires 0.0
file 0.0
final 0.0
free 0.0
gift 0.0
hawaii 0.0
headphones 0.0
help 0.0
hi 0.0
home 0.0
hours 0.0
immediately 0.0
instantly 0.0
iphone 0.0
just 0.0
know 0.0
laptop 0.0
let 0.0
limited 0.0
ll 0.0
loan 0.0
lunch 0.0
make 0.0
maldives 0.0
meeting 0.0
money 0.0
new 0.0
offer 0.0
order 0.0
paris 0.0
plan 0.0
pm 0.0
prescription 0.0
previous 0.0
prize 0.0
products 0.0
project 0.4640170318335872
received 0.0
reminder 0.0
report 0.4640170318335872
restore 0.0
review 0.0
scheduled 0.0
selected 0.0
send 0.0
sent 0.0
shipped 0.0
shop 0.0
smartwatch 0.0
soon 0.0
suspended 0.0
tablet 0.0
task 0.0
team 0.0
thanks 0.0
time 0.0
today 0.0
tomorrow 0.0
tonight 0.0
update 0.4640170318335872
urgent 0.0
vacation 0.0
ve 0.0
verify 0.0
version 0.0
week 0.37249533778745597
win 0.0
won 0.0
yesterday 0.0

Let's split the data in 80-20 set

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)
print(X_train.shape)
print(X_test.shape)

(200, 110)
(50, 110)

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
model =LogisticRegression()
model.fit(X_train,Y_train)

LogisticRegression()

In [14]:
print(accuracy_score(Y_test,model.predict(X_test)))

1.0